[bar.default]
capsule = true
center = [ "workspaces" ]
end = [ "tray", "notifications", "network", "bluetooth", "volume", "brightness", "battery", "control-center", "session" ]
font_family = "Iosevka NFM"
font_weight = 900
margin_edge = 5
margin_ends = 10
radius = 75
start = [ "clock", "launcher", "audio_visualizer", "media" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 640.0
    cy = 901.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 800.0
    cy = 776.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[osd.kinds]
lock_keys = false

[shell]
font_family = "AdwaitaMono Nerd Font Mono"
telemetry_enabled = true

[theme]
builtin = "Tokyo-Night"

[wallpaper]
directory = "/home/beamy/walls"

    [wallpaper.default]
    path = "/home/beamy/walls/wall7.jpg"

    [wallpaper.last]
    path = "/home/beamy/walls/wall7.jpg"

[widget.brightness]
show_label = false

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.workspaces]
hide_when_empty = true
labels_only_when_occupied = true